name: Docker

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_SOURCE: https://github.com/${{ github.repository }}

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . -f ./Dockerfile -t "${IMAGE_NAME}:server-monitor"
          docker build . -f ./Dockerfile.distroless -t "${IMAGE_NAME}:server-monitor-distroless"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          echo IMAGE_NAME=$IMAGE_NAME
          echo VERSION=$VERSION
          docker tag ${IMAGE_NAME}:server-monitor $IMAGE_NAME:$VERSION-server-monitor
          docker tag ${IMAGE_NAME}:server-monitor-distroless $IMAGE_NAME:$VERSION-server-monitor-distroless
          docker push $IMAGE_NAME:$VERSION-server-monitor
          docker push $IMAGE_NAME:$VERSION-server-monitor-distroless
